### ISSUE TITLE
[Discussion] Would that be possible for other presidents?

### ISSUE THREAD

**Issue by MaximRouiller** [DavidBuchanan314/trumpogram#1]
We need more.

**Comment by DavidBuchanan314** [comment]
If we ignore tweets, speech transcripts should be available going back quite a long way. It could take a bit of effort to collate them all though.

**Comment by DavidBuchanan314** [comment]
This could be of use: http://digital.lib.hkbu.edu.hk/corpus/index.php

However, they don't make it obvious how to actually obtain the raw data.

**Comment by MaximRouiller** [comment]
Hummmm... it looks like we could go about it by searching countries individually... not as easy.

**Comment by MaximRouiller** [comment]
Otherwise I found this website: http://www.presidency.ucsb.edu/2012_election.php

A bit of scrapping might be necessary
