### ISSUE TITLE
Permission request

### ISSUE THREAD

**Issue by 20jbonilla** [DavidBuchanan314/trumpogram#2]
Hi David, I'm interested in featuring your graphic in one of my firm's research publication. Would it be possible to obtain permission to use the graphic? I was looking for an email contact to reach you but couldn't find one. This is a time sensitive request as we are looking to publish By Monday. Apologies for the short notice but we just stumbled upon the graphic and would love to feature it in our report.

**Comment by DavidBuchanan314** [comment]
Sure! I'd appreciate it if you gave me some form of credit, either by mentioning my name or linking to this Github repo.

If you have any questions etc. I'd be happy to talk over email if you can give me your address (I'd rather not publish mine publicly).

I'd be interested to see your publication too.

**Comment by 20jbonilla** [comment]
Absolutely. Will provide any citations you'd  expect us to make. I'd rather not share my email either but will certainly reach out here if I have any question. Great stuff btw!

**Comment by 20jbonilla** [comment]
Hi David,

I hope this finds you well.

We are looking to do a 2019 edition of the Atlas you so kindly allowed us to use your terrific trump tweets map for (see email below).

Have you, by chance, updated it since the last version – maybe based on 2018 tweets or tweets since Trump’s election. If so, are you able to share it with us and can we use that in our new edition (as per terms below)?

Look forward to hearing from you.

Best

Tommy

Tommy Ricketts
Global Investment Strategist
BofA Merrill Lynch – MLPF&S
One Bryant Park
New York, NY 10036
+1 (646) 855-2842
tommy.ricketts@bankofamerica.com<mailto:tommy.ricketts@bankofamerica.com>

**Comment by DavidBuchanan314** [comment]
Sorry, I haven't updated it. But all the information to update and replicate it should be available in this repo.

**Comment by 20jbonilla** [comment]
Hi David

Just wanted to follow up on below email and see if an update is possible.

Best

Tommy

Tommy Ricketts
Global Investment Strategist
BofA Merrill Lynch – MLPF&S
One Bryant Park
New York, NY 10036
+1 (646) 855-2842
tommy.ricketts@bankofamerica.com<mailto:tommy.ricketts@bankofamerica.com>


From: Ricketts, Tommy H - RSCH AMRS
Sent: Monday, April 08, 2019 2:24 PM
To: DavidBuchanan314/trumpogram; DavidBuchanan314/trumpogram
Cc: Author; Ricketts, Tommy H - RSCH AMRS
Subject: Trumpogram Permission request - 2019

Hi David,

I hope this finds you well.

We are looking to do a 2019 edition of the Atlas you so kindly allowed us to use your terrific trump tweets map for (see email below).

Have you, by chance, updated it since the last version – maybe based on 2018 tweets or tweets since Trump’s election. If so, are you able to share it with us and can we use that in our new edition (as per terms below)?

Look forward to hearing from you.

Best

Tommy

Tommy Ricketts
Global Investment Strategist
BofA Merrill Lynch – MLPF&S
One Bryant Park
New York, NY 10036
+1 (646) 855-2842
tommy.ricketts@bankofamerica.com<mailto:tommy.ricketts@bankofamerica.com>

**Comment by DavidBuchanan314** [comment]
The ball is in your court, as per my last reply. PRs with updated dataset sources are welcome.
